# Generated by Django 6.0.4 on 2026-04-24 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='rpe',
            field=models.IntegerField(default=5, help_text='Rate of Perceived Exertion (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
