# Generated by Django 6.0.4 on 2026-04-27 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_alter_workout_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='distance_meters',
            field=models.IntegerField(help_text='Distance in meters', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='split',
            name='duration_seconds',
            field=models.IntegerField(help_text='Duration in seconds', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration_hours',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration_seconds',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.FloatField(help_text='Distance in kilometers', null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration_minutes',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='workout',
            name='rpe',
            field=models.IntegerField(default=5, help_text='Rate of Perceived Exertion (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
