# Generated by Django 6.0.4 on 2026-04-27 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_alter_workout_duration_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
