# Generated by Django 6.0.4 on 2026-05-04 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0008_userprofile_and_localdate_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='duration_minutes',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(default=0, help_text='Height in centimeters', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='intersertion',
            field=models.TextField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Weight in kilogrammes', max_digits=5, null=True),
        ),
    ]
