# Generated by Django 6.0.4 on 2026-05-04 15:41

from django.db import migrations


def merge_intersertion_into_last_name(apps, schema_editor):
    UserProfile = apps.get_model('runs', 'UserProfile')
    for profile in UserProfile.objects.exclude(intersertion__isnull=True).exclude(intersertion=''):
        profile.last_name = f"{profile.intersertion} {profile.last_name}".strip()
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0009_split_duration_minutes_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_intersertion_into_last_name, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userprofile',
            name='intersertion',
        ),
    ]
