# Generated by Django 6.0.4 on 2026-05-05 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0011_weightlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='distance_meters',
        ),
        migrations.AddField(
            model_name='split',
            name='distance',
            field=models.IntegerField(help_text='Distance in km', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
